runtime: nodejs22
env: standard
automatic_scaling:
  min_instances: 2
  max_instances: 2

handlers:
  # Serve static assets with caching
  - url: /assets/(.*)
    static_files: dist/assets/\1
    upload: dist/assets/.*
    secure: always
    http_headers:
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      Cache-Control: public, max-age=31536000

  # Serve font files with caching
  - url: /fonts/(.*)
    static_files: dist/fonts/\1
    upload: dist/fonts/.*
    secure: always
    http_headers:
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      Cache-Control: public, max-age=31536000

  # Fallback to Node.js server for all other routes
  - url: /.*
    script: auto
    secure: always
