runtime: nodejs22
env: standard
automatic_scaling:
  min_instances: 2
  max_instances: 2

handlers:
  # Serve static assets with caching
  - url: /assets
    static_dir: dist/public/assets
    secure: always
    expiration: 365d
    http_headers:
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY

  # Serve font files with caching
  - url: /fonts/
    static_dir: dist/public/fonts
    secure: always
    expiration: 365d
    http_headers:
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY

  # Fallback to Node.js server for all other routes
  - url: /.*
    script: auto
    secure: always
