steps:
  - name: 'node'
    entrypoint: 'pnpm'
    args: ['add', '-g', '@nestjs/cli']

  - name: 'node'
    entrypoint: 'pnpm'
    args: ['install']

  - name: 'node'
    entrypoint: 'pnpm'
    args: ['build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud app deploy --quiet']

options:
  logging: CLOUD_LOGGING_ONLY
