steps:
  - name: 'node:lts-alpine'
    entrypoint: 'npm'
    args: ['install', '-g', 'pnpm@pnpm@10.10.0']

  - name: 'node:lts-alpine'
    entrypoint: 'pnpm'
    args: ['add', '-g', '@nestjs/cli']

  - name: 'node:lts-alpine'
    entrypoint: 'pnpm'
    args: ['install']

  - name: 'node:lts-alpine'
    entrypoint: 'pnpm'
    args: ['build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud app deploy --quiet']

options:
  logging: CLOUD_LOGGING_ONLY
