steps:
  - name: "node:22"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        yarn global add @nestjs/cli && \
        yarn install && \
        touch ./apps/server/.env && \
        echo "MY_SECRET=${_TEST_VAR}" >> ./apps/server/.env && \
        yarn build

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: ["-c", "gcloud app deploy --quiet"]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TEST_VAR: ${_TEST_VAR}
