steps:
  - name: "note:lts-alpine"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Set environment variable to app
        yarn global add @nestjs/cli && \
        yarn install && \
        touch .env && \
        echo "MY_SECRET=${_TEST_VAR}" >> .env && \
        yarn build

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: ["-c", "gcloud app deploy --quiet"]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TEST_VAR: ${_TEST_VAR}
