steps:
  - name: "bash"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Set environment variable to app
        touch /workspace/apps/server/.env
        echo "MY_SECRET=${_TEST_VAR}" >> /workspace/apps/server/.env
        echo "Original: ${_TEST_VAR}, Uppercase: $_UPPERCASE"
        cat /workspace/apps/server/.env

  - name: "node:lts-alpine"
    entrypoint: "yarn"
    args: ["global", "add", "@nestjs/cli"]

  - name: "node:lts-alpine"
    entrypoint: "yarn"
    args: ["install"]

  - name: "node:lts-alpine"
    entrypoint: "yarn"
    args: ["build"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: ["-c", "gcloud app deploy --quiet"]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TEST_VAR: ${_TEST_VAR}
