steps:
  - name: "node:lts-alpine"
    script: |
      echo MY_SECRET=${_TEST_VAR} >> ./apps/server/.env
      cat ./apps/server/.env

  - name: "node:lts-alpine"
    entrypoint: "yarn"
    args: ["global", "add", "@nestjs/cli"]

  - name: "node:lts-alpine"
    entrypoint: "yarn"
    args: ["install"]

  - name: "node:lts-alpine"
    entrypoint: "yarn"
    args: ["build"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args: ["-c", "gcloud app deploy --quiet"]

options:
  logging: CLOUD_LOGGING_ONLY
