steps:
  - name: 'node:lts-alpine'
    entrypoint: 'yarn'
    args: ['install', '-g', '@nestjs/cli']

  - name: 'node:lts-alpine'
    entrypoint: 'yarn'
    args: ['install',]

  - name: 'node:lts-alpine'
    entrypoint: 'yarn'
    args: ['build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud app deploy --quiet']

options:
  logging: CLOUD_LOGGING_ONLY
