steps:
  - name: 'node:lts-alpine'
    entrypoint: 'npm'
    args: ['install', '-g', 'pnpm@10.10.0 @nestjs/cli']

  - name: 'node:lts-alpine'
    entrypoint: 'npm'
    args: ['install',]

  - name: 'node:lts-alpine'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud app deploy --quiet']

options:
  logging: CLOUD_LOGGING_ONLY
