services:

  api:
    build:
      context: apps/api
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    user: root
    command: sh -c 'apt-get update && apt-get install -y procps && npm install && npm run start:dev'
    working_dir: /usr/src/app
    volumes:
      - ./apps/api:/usr/src/app
      - ./apps/api/dist:/usr/src/app/dist
      - ./apps/api/node_modules:/usr/src/app/node_modules
    ports:
      - '4000:4000'
    env_file:
      - apps/api/.env

  www:
    build:
      context: apps/www
      dockerfile: Dockerfile
      target: development
    user: root
    command: sh -c 'npm install && npm run dev'
    working_dir: /usr/src/app
    volumes:
      - ./apps/www:/usr/src/app
      - ./apps/www/node_modules:/usr/src/app/node_modules
      - ./apps/www/.next:/usr/src/app/.next
    ports:
      - '3000:3000'
    env_file:
      - apps/www/.env

volumes:
  next:
    driver: local
  nest:
    driver: local