services:
  next:
    build:
      context: apps/next
      dockerfile: Dockerfile
      target: development
    command: sh -c 'npm install && npm run dev'
    working_dir: /usr/src/app
    volumes:
      - ./apps/next:/usr/src/app
    ports:
      - '3000:3000'
  nest:
    build:
      context: apps/server
      dockerfile: Dockerfile
      target: development
    command: sh -c 'npm install && npm run start:dev'
    working_dir: /usr/src/app
    volumes:
      - ./apps/server:/usr/src/app
    ports:
      - '4000:4000'

volumes:
  next:
    driver: local
  nest:
    driver: local