packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - sharp
  - unrs-resolver
